name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt install
      run: 
        sudo apt install git build-essential libboost-all-dev libcurl4-gnutls-dev liblzma-dev libz-dev libbz2-dev cmake

    - name: make
      run: 
        make
        
    - name: test
      run: 
        ssp -h

